### ISSUE TITLE
Problems at unlocking, doesn`t keep the public ETH wallet address

### ISSUE THREAD

**Issue by Nirgello** [DAppNinjas/Etheroll-for-Android#2]
I have an Android 7.1.1 at my BQ Aquarius X5 Plus.
To store my PWs I use Keypass2Android and your latest Etheroll for Android 1.01 opened in Chrome.

Now, when I pick up the ETH Wallet Private Key (= ETH public account address) from the Keypass2Android and copy it into the top field of Etheroll for Android its there.
BUT when I fetch now the ETH Wallet PW and want to paste into that field, the above entry of my ETH public address is gone. 

Means the entry for the public address isn`t kept until the PW is fetched.

Thats very annoying, as I can't unlock and use your very interesting App and test it because my PWs aren`t small and I can't memorize them at all = need to copy-paste them.

I'd by happy if you could fix this because I'd rather like to test your promising App!

BTW I'd like to see your App remaned into Etheroll4Android. Sounds and reads cooler. But thats just my opinion.

**Comment by DAppNinjas** [comment]
So first things first, unless I'm mistaken, I believe you are putting in the wrong data in the first field. You need to put in your private key (not your public Ethereum address) the private key is the secret and typically ~64 characters. That goes in the first field. The second field is a password you need to create and set for the app (to both access the app and your private key in first field). You should be able to type a password in the second field (one that you can remember because you will be required to enter it everytime you open the app).

**Comment by DAppNinjas** [comment]
Going to close this as it seems like it was a problem with what was being entered as mentioned above.
